---
title: "CC "
author: "Tiffany Sun (tsun28@amherst.edu)"
format: 
  pdf:
    toc: true
date: "`r Sys.Date()`"
editor: source
knitr:
  opts_chunk:
    fig.align: center
---

```{r}
#| label: packages
#| echo: FALSE
#| message: FALSE

knitr::opts_chunk$set(   
  message = FALSE)   

library(tidyverse)
library(vroom)
library(tidygeocoder)
library(maps)
library(ggrepel)
library(sf)
library(tictoc)

my_sf <- read_sf("UHF42.geo.json") |>
  janitor::clean_names()

census_records <- readRDS("census_records.rds")

```

```{r}
#| label: data

data <- vroom("Motor_Vehicle_Collisions_-_Crashes_20260612.csv") |>
    janitor::clean_names() |>
    mutate(crash_date = as.Date(crash_date, format="%m/%d/%Y"),
    longitude = ifelse(is.na(longitude), census_records$longitude[match(on_street_name, census_records$on_street_name)], longitude),
    latitude = ifelse(is.na(latitude), census_records$latitude[match(on_street_name, census_records$on_street_name)], latitude))

data$year <- year(data$crash_date)
  
coords <- data |>
  select(c(longitude, latitude, number_of_persons_injured, number_of_persons_killed)) |>
  filter(!is.na(longitude), !is.na(latitude), latitude != 0, longitude != 0) |>
  mutate(longitude = ifelse(longitude < -200, yes =longitude + 127.2832727, longitude))
  
```

```{r}
#| label: map

ggplot(my_sf) +
  geom_sf(fill = "white", color = "black", linewidth = 0.1) +
  theme_void()

data_sf <- st_as_sf(
  coords,
  coords = c("longitude", "latitude"),
  crs = 4326
) |>
  st_make_valid()

my_sf <- my_sf |> st_make_valid()

data_sf <- st_transform(data_sf, st_crs(my_sf))

  st_crs(data_sf)
  st_crs(my_sf)

tic()
counts <- lengths(st_intersects(my_sf , data_sf |> select(geometry)))
toc()

tic()
joined <- st_intersection(my_sf, data_sf)
toc()

my_sf$n <- counts

  ggplot(my_sf) +
  geom_sf(aes(fill = n), color = "black", linewidth = 0.1) +
  theme_void()

geom_sf()

```

```{r}
#| label: analysis

# Top ten neighborhoods with most vehicle collisions
my_sf |>
  mutate(my_sf, geoname = fct_reorder(geoname, n)) |>
  arrange(desc(n)) |>
  slice(1:10) |>
  ggplot(
    aes(geoname, n)
  ) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Top Ten Neighborhoods with Most Vehicle Collisions",
    y = "Neighborhoods",
    x = "Collisions"
  )


# Boroughs with most vehicle collisons
my_sf |>
  filter(
    borough != "N/A"
  ) |>
  group_by(borough) |>
  summarize(
    ct = sum(n)
  ) |>
  mutate(borough = fct_reorder(borough, ct)) |>
  arrange(desc(ct)) |>
  slice(1:10) |>
  ggplot(
    aes(borough, ct)
  ) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Ranked Boroughs with Most Vehicles Collisions",
    y = "Borough",
    x = "Collisions"
  )

  # Casualties

```

