---
title: "CC "
author: "Tiffany Sun (tsun28@amherst.edu)"
format: 
  pdf:
    toc: true
date: "`r Sys.Date()`"
editor: source
knitr:
  opts_chunk:
    fig.align: center
---

```{r}
#| label: packages
#| echo: FALSE
#| message: FALSE

knitr::opts_chunk$set(   
  message = FALSE)   

library(tidyverse)
library(vroom)
library(tidygeocoder)
library(maps)
library(ggrepel)
library(sf)
library(tictoc)
library(janitor)
library(leaflet)

```

```{r}
my_sf <- read_rds("data/my_sf.rds") 
data <- read_rds("data/collisions_data.rds") 

```

```{r}
# all chloropleth map of NYC collisions , slider of years

# Define a color palette
pal <- colorNumeric(
  palette = "YlOrRd", 
  domain = my_sf$deaths
)

# Create the map
leaflet(my_sf) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~pal(count),
    fillOpacity = 0.8,
    color = "white",
    weight = 1,
    popup = paste0("Region: ", my_sf$geoname, "<br>Value: ", my_sf$count)
  )   


ggplot(my_sf) +
geom_sf(aes(fill = count)) +
  theme_void()

s <-  data |> group_by(crash_date, geometry, geoname, borough) |>
    summarize(count = n(),
    deaths = sum(number_of_persons_killed),
    injuries = sum(number_of_persons_injured),
    .groups = "drop") |> 
    group_by(geometry, geoname, borough) |>
    summarize(count = sum(count),
    deaths = sum(deaths),
    injuries = sum(injuries), 
    .groups = "drop") |> 
    st_as_sf()
  
leaflet(s) |>
    addTiles() |>
    addPolygons(
    fillColor = ~pal(deaths),
    fillOpacity = 0.8,
    color = "white",
    weight = 1,
    popup = ~paste0("Region: ", geoname, "<br>Value: ", deaths))

  data |> group_by(crash_date, geometry) |>
    summarize(pedestrians = sum(number_of_pedestrians_killed),
              motorists = sum(number_of_motorist_killed),
              cyclists = sum(number_of_cyclist_killed),
              deaths = sum(number_of_persons_killed)) |>
    group_by(geometry) |>
    summarize(pedestrians = sum(pedestrians),
    motorists = sum(motorists),
    cyclists = sum(cyclists),
    deaths = sum(deaths)) |>
    pivot_longer(
    cols = -c(geometry, deaths),
    names_to = "category",
    values_to = "casualties"
  ) |>
    st_as_sf() |>
    ggplot() +
    geom_sf(aes(fill = deaths)) +
    theme_void()



# Top ten neighborhoods with most vehicle collisions
# slider of years 
my_sf |>
  mutate(my_sf, geoname = fct_reorder(geoname, count)) |>
  arrange(desc(count)) |>
  slice(1:10) |>
  ggplot(
    aes(geoname, count)
  ) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Top Ten Neighborhoods with Most Vehicle Collisions",
    y = "Neighborhoods",
    x = "Collisions"
  )

# Boroughs with most vehicle collisons
# slider of years
my_sf |>
  filter(
    borough != "N/A"
  ) |>
  group_by(borough) |>
  summarize(
    ct = sum(count)
  ) |>
  mutate(borough = fct_reorder(borough, ct)) |>
  arrange(desc(ct)) |>
  slice(1:10) |>
  ggplot(
    aes(borough, ct)
  ) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Ranked Boroughs with Most Vehicles Collisions",
    y = "Borough",
    x = "Collisions"
  )

  # number of collisions across time
  # dropdown: boroughs, geonames 
  # slider of years
  data |> group_by(crash_date) |>
    summarize(count = n()) |> 
    ggplot(aes(x=crash_date, y=count)) +
    geom_line() + 
    xlab("")

#filter(between(crash_date, as.Date("2014-01-20"), as.Date("2014-01-27"))) 

# injured
data |> group_by(borough) |>
    summarize(number_of_persons_injured = sum(number_of_persons_injured)) |>
  mutate(borough = fct_reorder(borough, number_of_persons_injured)) |>
  ggplot(aes(x = borough, y = number_of_persons_injured)) +
  geom_col() +
  coord_flip()

# killed 
data |> group_by(borough) |>
  summarize(number_of_persons_killed = sum(number_of_persons_killed)) |>
  mutate(borough = fct_reorder(borough, number_of_persons_killed)) |>
  ggplot(aes(x = borough, y = number_of_persons_killed)) +
  geom_col() +
  coord_flip()

# Reasons 
data |> filter(contributing_factor_vehicle_1 != "Unspecified") |> group_by(contributing_factor_vehicle_1) |>
  summarize(n = n()) |>
  mutate(contributing_factor_vehicle_1 = fct_reorder(contributing_factor_vehicle_1, n)) |>
  arrange(desc(n)) |>
  slice(1:10) |> 
  ggplot(aes(contributing_factor_vehicle_1, n)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Top Ten Reasons",
    y = "Count",
    x = "Contributing Reason"
  )

# 
```